<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Capa_Controlador_Seguridad">
      <HintPath>..\..\..\componentes\seguridad\SeguridadMVC\SeguridadMVC\CapaControlador\bin\Debug\Capa_Controlador_Seguridad.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_actividades_pro">
      <HintPath>..\..\..\Grupo1_Mantenimientos\Mantenimientos_Actividades_Proyectos\MVC_Mantenimiento_Actividades_Proyecto\Capa_Vista_actividades_pro\bin\Debug\Capa_Vista_actividades_pro.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_Areas">
      <HintPath>..\..\..\Grupo1_Mantenimientos\Mant Areas\MVC_MANT_AREAS\Capa_Vista_Areas\bin\Debug\Capa_Vista_Areas.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_PE">
      <HintPath>..\..\..\Grupo1_Mantenimientos\Mnt\Mnt_PE\Capa_Vista_PE\bin\Debug\Capa_Vista_PE.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_PY">
      <HintPath>..\..\..\Grupo1_Mantenimientos\DLLs\DLL_Proyecto\Capa_Vista_PY\bin\Debug\Capa_Vista_PY.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_Recursos">
      <HintPath>..\..\..\Grupo1_Mantenimientos\DLLs\Mantenimiento_Recursos\Capa_Vista_Recursos\bin\Debug\Capa_Vista_Recursos.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>