<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Capa_Controlador_Seguridad">
      <HintPath>..\..\..\componentes\seguridad\SeguridadMVC\SeguridadMVC\CapaControlador\bin\Debug\Capa_Controlador_Seguridad.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_Criterios">
      <HintPath>..\..\..\Grupo_3\Mantenimientos\Criterios\Capa_Vista_Criterios\bin\Debug\Capa_Vista_Criterios.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_Escalas">
      <HintPath>..\..\..\Grupo_3\Mantenimientos\Mantenimiento_Escalas\Capa_Vista_Escalas\bin\Debug\Capa_Vista_Escalas.dll</HintPath>
    </Reference>
    <Reference Include="Capa_Vista_Rubrica">
      <HintPath>..\..\..\Grupo_3\Mantenimientos\Mantenimiento_Rubrica\Capa_Vista_Rubrica\bin\Debug\Capa_Vista_Rubrica.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>